=== adacine2/PLANNER-javafx/src/main/resources/cz/vse/planner/utils/library.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="library" type="LibraryType"/>

    <xs:complexType name="LibraryType">
        <xs:sequence>
            <xs:element name="book" type="BookType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="BookType">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="year" type="YearType"/>
            <xs:element name="isbn" type="ISBNType"/>
            <xs:element name="category" type="CategoryType"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="YearType">
        <xs:restriction base="xs:integer">
            <xs:totalDigits value="4"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ISBNType">
        <xs:restriction base="xs:string">
            <xs:pattern value="ISBN \d+-\d+-\d+-\d+-\d+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CategoryType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="beletrie"/>
            <xs:enumeration value="sci-fi"/>
            <xs:enumeration value="filozofie"/>
            <xs:enumeration value="učebnice"/>
            <xs:enumeration value="poezie"/>
            <!-- pripadne dodej dalsi kategorie -->
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== adacine2/PLANNER-javafx/src/main/resources/cz/vse/planner/utils/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="library.xsd">
<book>
    <name>Kytice</name>
    <year>1853</year>
    <isbn>ISBN 8-77-88-22-3</isbn>
    <category>poezie</category>
</book>
<book>
    <name>LOTR</name>
    <year>1954</year>
    <isbn>ISBN 2332-2778-726652-99-0</isbn>
    <category>sci-fi</category>
</book>
</library>
