=== adacine2/PLANNER-javafx/src/main/resources/cz/vse/planner/utils/modely.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<!-- SHOP celkem, obsahuje SHOPITEMy-->

    <xs:element name="SHOP">

        <xs:complexType>
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" ref="SHOPITEM"/>
        </xs:sequence>
        </xs:complexType>

    </xs:element>

<!-- SHOPITEMy definice -->

    <xs:element name="SHOPITEM">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Model" type="Model" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Model">
        <xs:all>
            <xs:element name="Název" type="xs:string"/>
            <xs:element name="Druh" type="DruhTyp" minOccurs="0"/>
            <xs:element name="Měřítko" type="xs:string"/>
            <xs:element name="Žel.správa" type="xs:string" minOccurs="0"/>
            <xs:element name="Epocha" type="EpochaTyp"/>
            <xs:element name="Edice" type="xs:string"/>
            <xs:element name="Přezdívka" type="xs:string" minOccurs="0"/>
            <xs:element name="DCC_konektor" type="DCCTyp" minOccurs="0"/>
            <xs:element name="Délka" type="DelkaTyp"/>
            <xs:element name="Poloměr" type="PolomerTyp" minOccurs="0"/>
            <xs:element name="Osvětlení" type="xs:string" minOccurs="0"/>
            <xs:element name="Stát" type="xs:string"/>
            <xs:element name="Výrobce" type="xs:string"/>
            <xs:element name="Čís.produktu" type="CisTyp"/>
            <xs:element name="Cena" type="CenaTyp" />
            <xs:element name="Skladem" type="SkladTyp"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="CisTyp">
        <xs:restriction base="xs:integer">
            <xs:totalDigits value="9"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="EpochaTyp">
        <xs:restriction base="xs:string">
            <xs:totalDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="DCCTyp">
        <xs:restriction base="xs:string">
            <xs:pattern value="(Ano|Ne)\s*.*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="DruhTyp">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Elektrická Lokomotiva"/>
            <xs:enumeration value="Motorová Lokomotiva"/>
            <xs:enumeration value="Parní Lokomotiva"/>
            <xs:enumeration value="Elektrická Jednotka"/>
            <xs:enumeration value="Motorová Jednotka"/>
            <xs:enumeration value="Vagón"/>
            <xs:enumeration value="Osobní automobil"/>
            <xs:enumeration value="Nákladní automobil"/>
            <xs:enumeration value="Autobus"/>
            <xs:enumeration value="Tramvaj"/>
            <xs:enumeration value="Ostatní"/>
            <!-- popřípadě další -->
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="DelkaTyp">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d+mm"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="PolomerTyp">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d+mm"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="CenaTyp">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d+(Kč|€)"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="SkladTyp">
        <xs:sequence>
                    <xs:element name="SklademJe" type="SklademJeTyp"/>
                    <xs:element name="SklademKs" type="SklademKsTyp" minOccurs="0"/>
                    <xs:element name="Expedice" type="ExpediceTyp" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="SklademKsTyp">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d+(Ks|ks)?"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="SklademJeTyp">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Ano"/>
            <xs:enumeration value="Ne"/>
            <xs:enumeration value="Předobjednávka"/>
            <xs:enumeration value="Na cestě"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ExpediceTyp">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}[.-]\d{2}[.-]\d{4}"/>
        </xs:restriction>
    </xs:simpleType>



</xs:schema>

=== adacine2/PLANNER-javafx/src/main/resources/cz/vse/planner/utils/modely.xml
<?xml version="1.0" encoding="UTF-8"?>
<SHOP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modely.xsd">
    <SHOPITEM>
        <Model>
            <Název>H0 - elektrická lokomotiva Vectron Metrans</Název>
            <Druh>Elektrická Lokomotiva</Druh>
            <Měřítko>H0</Měřítko>
            <Žel.správa>METRANS</Žel.správa>
            <Epocha>VI</Epocha>
            <Edice>PIKO EXPERT</Edice>
            <Přezdívka>Vectron</Přezdívka>
            <DCC_konektor>Ano NEM 658 Plux22</DCC_konektor>
            <Délka>218mm</Délka>
            <Poloměr>358mm</Poloměr>
            <Osvětlení>bílá / červená</Osvětlení>
            <Stát>Česko</Stát>
            <Výrobce>PIKO</Výrobce>
            <Čís.produktu>21605</Čís.produktu>
            <Cena>4990Kč</Cena>
            <Skladem>
                <SklademJe>Ano</SklademJe>
                <SklademKs>3Ks</SklademKs>
            </Skladem>
        </Model>
    </SHOPITEM>

    <SHOPITEM>
        <Model>
            <Název>H0 - elektrická lokomotiva Vectron Regiojet CZ</Název>
            <Druh>Elektrická Lokomotiva</Druh>
            <Měřítko>H0</Měřítko>
            <Žel.správa>RegioJet CZ/SK</Žel.správa>
            <Epocha>VI</Epocha>
            <Přezdívka>Vectron</Přezdívka>
            <Edice>PIKO EXPERT</Edice>
            <DCC_konektor>Ano NEM 658 Plux22</DCC_konektor>
            <Délka>218mm</Délka>
            <Poloměr>358mm</Poloměr>
            <Stát>Česko, Slovensko</Stát>
            <Výrobce>PIKO</Výrobce>
            <Čís.produktu>59591</Čís.produktu>
            <Cena>5990Kč</Cena>
            <Skladem>
                <SklademJe>Ano</SklademJe>
                <SklademKs>5Ks</SklademKs>
            </Skladem>
        </Model>
    </SHOPITEM>
    <SHOPITEM>
        <Model>
            <Název>H0 - el. lokomotiva Vectron ZSSK "SPOLOČNÁ CESTA K ÚSPECHU"</Název>
            <Druh>Elektrická Lokomotiva</Druh>
            <Měřítko>H0</Měřítko>
            <Žel.správa>ZSSK Slovensko</Žel.správa>
            <Epocha>VI</Epocha>
            <Edice>PIKO EXPERT</Edice>
            <Přezdívka>Vectron</Přezdívka>
            <DCC_konektor>Ano NEM 658 Plux22</DCC_konektor>
            <Délka>218mm</Délka>
            <Poloměr>358mm</Poloměr>
            <Stát>Slovensko</Stát>
            <Výrobce>PIKO</Výrobce>
            <Čís.produktu>59197</Čís.produktu>
            <Skladem>
                    <SklademJe>Předobjednávka</SklademJe>
                    <Expedice>08.11.2019</Expedice>
            </Skladem>
            <Cena>6790Kč</Cena>
        </Model>
    </SHOPITEM>
    <SHOPITEM>
        <Model>
            <Název>H0 - vůz Business-internet café RegioJet</Název>
            <Druh>Vagón</Druh>
            <Měřítko>H0</Měřítko>
            <Žel.správa>RegioJet CZ/SK</Žel.správa>
            <Epocha>VI</Epocha>
            <Edice>A.C.M.E.</Edice>
            <Přezdívka>Business-internet café</Přezdívka>
            <DCC_konektor>Ne</DCC_konektor>
            <Délka>303mm</Délka>
            <Stát>Česko</Stát>
            <Výrobce>A.C.M.E.</Výrobce>
            <Čís.produktu>52647</Čís.produktu>
            <Cena>1990Kč</Cena>
            <Skladem>
                <SklademJe>Ano</SklademJe>
                <SklademKs>2ks</SklademKs>
            </Skladem>
        </Model>
    </SHOPITEM>
</SHOP>
